### PR TITLE
Correction for errors and warnings issued with GCC 13

### PR DESCRIPTION
**Pull request by titixbrest**

### CODE REVIEW

**Comment by pardo-bsso** [comment]
(take this from someone that does not have commit rights here)

Overall looks good. Have you tested that it still compiles fine with previous versions?

**Comment by titixbrest** [comment]
no I did not test this patch on older compiler releases, sorry

**Comment by pat1** [comment]
gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)
compile OK

without this pull request compilation abort

**Comment by rafael2k** [comment]
I'll commit and we see if there are any side-effects.

**Comment by titixbrest** [comment]
Hi Rafael,
On my setup it runs for 2 weeks without trouble on a raspberry pi 3.

Thanks !

**Comment by rafael2k** [comment]
Thank you!
: )

**Pull request merged**
